---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/articles
  label: Articles
  create: documents
  match: "**/*"
  templates:
  - article-template
- type: directory
  path: content/categories
  label: Categories
  create: documents
  match: "**/*"
  templates:
  - category-template
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.53'
